// eslint-disable-next-line import/prefer-default-export
export const Dumy = {
  total_count: 85,
  current_count: 10,
  total_page: 9,
  current_page: 1,
  tests: [
    {
      id: 1,
      status: 'close',
      creater: '송선권',
      team: 'campus',
      title: '식단 테스트',
      created_at: '2024-07-30',
      updated_at: '2024-07-31',
    },
    {
      id: 2,
      status: 'close',
      creater: '송선권1',
      team: 'campus',
      title: '식단 테스트',
      created_at: '2024-07-30',
      updated_at: '2024-07-31',
    },
    {
      id: 3,
      status: 'close',
      creater: '송선권2',
      team: 'campus',
      title: '식단 테스트',
      created_at: '2024-07-30',
      updated_at: '2024-07-31',
    },
    {
      id: 4,
      status: 'close',
      creater: '송선권',
      team: 'campus',
      title: '식단 테스트',
      created_at: '2024-07-30',
      updated_at: '2024-07-31',
    },
    {
      id: 5,
      status: 'close',
      creater: '송선권1',
      team: 'campus',
      title: '식단 테스트',
      created_at: '2024-07-30',
      updated_at: '2024-07-31',
    },
    {
      id: 6,
      status: 'close',
      creater: '송선권2',
      team: 'campus',
      title: '식단 테스트',
      created_at: '2024-07-30',
      updated_at: '2024-07-31',
    },
    {
      id: 7,
      status: 'close',
      creater: '송선권',
      team: 'campus',
      title: '식단 테스트',
      created_at: '2024-07-30',
      updated_at: '2024-07-31',
    },
    {
      id: 8,
      status: 'close',
      creater: '송선권1',
      team: 'campus',
      title: '식단 테스트',
      created_at: '2024-07-30',
      updated_at: '2024-07-31',
    },
    {
      id: 9,
      status: 'close',
      creater: '송선권2',
      team: 'campus',
      title: '식단 테스트',
      created_at: '2024-07-30',
      updated_at: '2024-07-31',
    },
    {
      id: 10,
      status: 'close',
      creater: '송선권',
      team: 'campus',
      title: '식단 테스트',
      created_at: '2024-07-30',
      updated_at: '2024-07-31',
    },
  ],
};
