yarnPath: .yarn/releases/yarn-3.8.0.cjs
nodeLinker: "pnp"

packageExtensions:
  '@toast-ui/editor@*':
    dependencies:
      prosemirror-transform: '*'
  '@toast-ui/react-editor@*':
    dependencies:
      prosemirror-transform: '*'